# Generated by Django 5.0.1 on 2024-02-04 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Überschrift')),
                ('slug', models.SlugField(verbose_name='Schlagwort')),
                ('body', models.TextField(verbose_name='Inhalt')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='veröffentlicht')),
                ('created', models.DateTimeField(verbose_name='erstellt')),
                ('updated', models.DateTimeField(verbose_name='angepasst')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx')],
            },
        ),
    ]
